server:
  port: 8085
  servlet:
    context-path: /api/ms-order

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce_order_db?useSSL=false&serverTimezone=America/Lima
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: America/Lima
  sql:
    init:
      mode: never

logging:
  level:
    org.springframework.security: DEBUG